import Link from "next/link";

export function Hero() {
  return (
    <section className="max-w-6xl mx-auto px-6 pt-20 pb-24 md:pt-32 md:pb-32">
      <div className="max-w-3xl">
        <div className="label mb-6">A study tool for your own documents</div>
        <h1 className="display text-5xl md:text-6xl lg:text-7xl leading-[1.03] mb-6">
          Study from your own documents. Retain more.
        </h1>
        <p className="text-lg text-[color:var(--muted)] max-w-xl leading-relaxed mb-10">
          Upload a PDF. Get flashcards, a structured study guide, and automated notes — generated by the AI model of your choice.
        </p>
        <div className="flex items-center gap-4 flex-wrap">
          <Link
            href="/app"
            className="bg-[color:var(--ink)] text-[color:var(--canvas)] px-7 py-3 rounded-sm text-sm font-medium hover:opacity-90 transition-opacity"
          >
            Try it free →
          </Link>
          <a
            href="#demo"
            className="border border-[color:var(--ink)] text-[color:var(--ink)] px-7 py-3 rounded-sm text-sm font-medium hover:bg-[color:var(--ink)] hover:text-[color:var(--canvas)] transition-colors"
          >
            See how it works
          </a>
        </div>
      </div>
    </section>
  );
}
