import type { Metadata } from "next";
import { Inter, Fraunces } from "next/font/google";
import "./globals.css";
import { ThemeToaster } from "@/components/theme-toaster";
import { ThemeProvider } from "next-themes";
import { DemoSeedProvider } from "./_demo-seed-provider";
import { PostHogProvider } from "@/components/posthog-provider";

const inter = Inter({ subsets: ["latin"] });
const fraunces = Fraunces({
  variable: "--font-display",
  subsets: ["latin"],
  axes: ["opsz"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "exam-helper — Study from your own documents",
  description:
    "Upload a PDF. Get flashcards, a structured study guide, and automated notes — generated by the AI model of your choice.",
  openGraph: {
    title: "exam-helper — Study from your own documents",
    description:
      "Upload a PDF. Get flashcards, a structured study guide, and automated notes — generated by the AI model of your choice.",
    url: "https://exam-helper.vercel.app",
    siteName: "exam-helper",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "exam-helper — Study from your own documents",
    description:
      "Upload a PDF. Get flashcards, a structured study guide, and automated notes.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body className={`${inter.className} ${fraunces.variable}`}>
        <PostHogProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <DemoSeedProvider>
              <ThemeToaster />
              {children}
            </DemoSeedProvider>
          </ThemeProvider>
        </PostHogProvider>
      </body>
    </html>
  );
}
