import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";
import { DemoSeedProvider } from "./_demo-seed-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "exam-helper — Study from your own documents",
  description:
    "Upload a PDF. Get flashcards, a structured study guide, and automated notes — generated by the AI model of your choice.",
  openGraph: {
    title: "exam-helper — Study from your own documents",
    description:
      "Upload a PDF. Get flashcards, a structured study guide, and automated notes — generated by the AI model of your choice.",
    url: "https://exam-helper.vercel.app",
    siteName: "exam-helper",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "exam-helper — Study from your own documents",
    description:
      "Upload a PDF. Get flashcards, a structured study guide, and automated notes.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <DemoSeedProvider>
            <Toaster />
            {children}
          </DemoSeedProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
